# .air.toml
root = "."
tmp_dir = "tmp"

[build]
# Binary file yields from `go build`
bin = "./tmp/main"
# Customize binary
full_bin = "./tmp/main"
# Watch these directories and files for changes
include_ext = ["go", "env"]
# Ignore these directories and files
exclude_dir = ["tmp", "vendor", ".git"]
# This log file places in your tmp_dir
log = "air.log"
# It's not necessary to trigger build each time file changes
delay = 1000 # ms
# Stop running old binary when build errors occur
stop_on_error = true
# Send Interrupt signal before killing process (Windows does not support this feature)
send_interrupt = false

[log]
# Show log time
time = true

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true 